### PR TITLE
Sudoku example

### PR DESCRIPTION
**Pull request by alex-cornejo**
Contains an implementation of a GA for the sudoku.
Contains a custom crossover.
Provides four different boards for testing.
Important sections of code are documented.

### CODE REVIEW

**Comment by jenetics** [comment]
Hi @alex-cornejo,

Thank you for the PR. After a short look at the code and have some general comments. You created the PR from the current master, but I will not create another 6.x version of the library. Could you please base the example on the r7.0.0 branch. This upcoming version will use Java17 and has already a lot of differences to the master branch. This will make it easier for me to do the merge. The second thing is about code formatting. Although I have not formal style guide specified, could you please use consistent indention (tabs)? As I saw you are also using 2-space deep indentations. And the opening curly brace is usually placed in the same line.

To the code itself: I would try to create an immutable representation of the Sudoku-Bord, which would make the code more readable and you could separate the domain-logic from the GA code more cleanly.

I hope this first comments were helpful :)

Regards
Franz

**Comment by alex-cornejo** [comment]
> Hi @alex-cornejo,
> 
> Thank you for the PR. After a short look at the code and have some general comments. You created the PR from the current master, but I will not create another 6.x version of the library. Could you please base the example on the r7.0.0 branch. This upcoming version will use Java17 and has already a lot of differences to the master branch. This will make it easier for me to do the merge. The second thing is about code formatting. Although I have not formal style guide specified, could you please use consistent indention (tabs)? As I saw you are also using 2-space deep indentations. And the opening curly brace is usually placed in the same line.
> 
> To the code itself: I would try to create an immutable representation of the Sudoku-Bord, which would make the code more readable and you could separate the domain-logic from the GA code more cleanly.
> 
> I hope this first comments were helpful :)
> 
> Regards Franz

Hi, thanks so much for the feedback. I will close this PR and create another one based on the r7.0.0 branch. 
Besides, I will consider the other changes you mentioned. I am still new in this library, but I want to learn to use good practices with it.

**Comment by alex-cornejo** [comment]
> > Hi @alex-cornejo,
> > Thank you for the PR. After a short look at the code and have some general comments. You created the PR from the current master, but I will not create another 6.x version of the library. Could you please base the example on the r7.0.0 branch. This upcoming version will use Java17 and has already a lot of differences to the master branch. This will make it easier for me to do the merge. The second thing is about code formatting. Although I have not formal style guide specified, could you please use consistent indention (tabs)? As I saw you are also using 2-space deep indentations. And the opening curly brace is usually placed in the same line.
> > To the code itself: I would try to create an immutable representation of the Sudoku-Bord, which would make the code more readable and you could separate the domain-logic from the GA code more cleanly.
> > I hope this first comments were helpful :)
> > Regards Franz
> 
> Hi, thanks so much for the feedback. I will close this PR and create another one based on the r7.0.0 branch. Besides, I will consider the other changes you mentioned. I am still new in this library, but I want to learn to use good practices with it.

Trying to setup branch r7.0.0. I am getting some issues:
```
Execution failed for task ':buildSrc:jar'.
> Entry META-INF/gradle-plugins/lyx.properties is a duplicate but no duplicate handling strategy has been set. Please refer to https://docs.gradle.org/7.3.1/dsl/org.gradle.api.tasks.Copy.html#org.gradle.api.tasks.Copy:duplicatesStrategy for details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
```

Some clue of how can I solve it? Could it be due to my IDE settings?
I am using IntelliJ IDEA 2021.3 with oracle jdk-17 on Windows 11

**Comment by alex-cornejo** [comment]
I finally was able to successfully setup the branch of version 7.X.X.
However, this example is not working anymore at version 7.X.X. 

I think a change in the library core was the cause, since in version 6.X the example works quite fine without any crucial modification.

**Comment by jenetics** [comment]
It might be this change: #787.  The upper limits for Integer/LongGenes are now  exclusively. This is the only **incompatible** change.

**Comment by alex-cornejo** [comment]
Since I created a new PR (https://github.com/jenetics/jenetics/pull/816) with these suggestions, I am closing this PR. Any discussion would please be followed in the new PR.

**Pull request closed without merging**
